# Generated by Django 4.2.4 on 2023-08-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_post_image_post_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='post_images/default.jpg', null=True, upload_to='post_images/'),
        ),
    ]
