# Generated by Django 4.2.4 on 2023-08-19 09:14

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=main_app.models.default_image_path, null=True, upload_to='post_images/'),
        ),
    ]
